openapi: 3.0.1
info:
  title: Ylab Monitoring API
  version: 1.0.0
servers:
  - url: http://localhost:9090/monitoring-app-springmvc-1.0.0/api
    description: Local
    variables: { }
security:
  - Bearer: [ ]
tags:
  - name: readings
  - name: auth
  - name: audit
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      scheme: Bearer
